# Basic
title: 爱我，爱你，爱自己
subtitle: 个人站
description: 欢迎来到我的个人站~
# 头像里面的标题
avatarTitle: aiwiown
# 头像里面的描述
avatarDesc: JAVA / 其他
url: "https://blog.aiwiown.com/"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
# comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    # disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    gitee: dbin0123
    # weibo: 5366874726 
    github: dbin0123
    # zhihu: panpanleopard
    # juejin: xxx
    # jianshu: 2ada30d8d0f7
    # twitter: 
    mail: dbin0123@hotmail.com


# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 15ff47592d52309a90efe9e6975528ae  

# Google Analytics
# 使用博客模板请去掉或者更换 id
# ga:
#     id: UA-84134159-3  
#     host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
# 支持的颜色：蓝色、绿色、紫色、红色、橙色或石板色。如果你需要清理，让它空着。
cover_color: clear

# The blog button should not be removed.
# 不应删除“博客”按钮。
blog_button:
    title: 爱我，爱你，爱自己

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
#    - {title: 技术支持, description: support, url: '/support'}      
    - {title: 关于我, description: about, url: '/about'}   
    

# Pagination 分页信息
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


